version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: db
    volumes:
      - ./postgres:/var/lib/postgresql
    networks:
      - mynet
  web:
    build: .
    depends_on:
     - db
    networks:
      - mynet
      
networks:
  mynet:
    driver: bridge